# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='units',
        ),
        migrations.AddField(
            model_name='departments',
            name='units',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.Units'),
        ),
    ]
