# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180501_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='l1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='l2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
