# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180303_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='units',
        ),
        migrations.AddField(
            model_name='departments',
            name='units',
            field=models.ManyToManyField(null=True, related_name='departmentsHeading', to='organization.Units'),
        ),
    ]
