# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20180303_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='divisionhead',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='emp_photo',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='reporting_manager',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='telephone',
        ),
    ]
