# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180603_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='fax',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
