# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180603_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
