# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180321_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='contacts',
            field=models.ManyToManyField(related_name='departmentsHeading', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departments',
            name='units',
            field=models.ManyToManyField(related_name='departmentsHeading', to='organization.Units'),
        ),
        migrations.AlterField(
            model_name='division',
            name='contacts',
            field=models.ManyToManyField(null=True, related_name='divisionsHeading', to=settings.AUTH_USER_MODEL),
        ),
    ]
