# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 12:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0006_auto_20180603_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('target', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('yearly', 'yearly'), ('quaterly', 'quaterly'), ('monthly', 'monthly'), ('weekly', 'weekly'), ('daily', 'daily')], default='yearly', max_length=20)),
                ('weightage', models.IntegerField(null=True)),
                ('assignedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KRAAssigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KRAProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField()),
                ('source', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KRAAwarded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200, null=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='responsibilities', to='organization.Departments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilitiesCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='kra',
            name='progress',
            field=models.ManyToManyField(blank=True, related_name='KRA', to='organization.KRAProgress'),
        ),
        migrations.AddField(
            model_name='kra',
            name='responsibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KRAs', to='organization.Responsibility'),
        ),
        migrations.AddField(
            model_name='kra',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KRA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kra',
            unique_together=set([('user', 'responsibility')]),
        ),
    ]
