# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180321_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='contacts',
            field=models.ManyToManyField(related_name='divisionsHeading', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='units',
            name='contacts',
            field=models.ManyToManyField(related_name='unitsHeading', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='units',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organization.Division'),
        ),
    ]
