# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180613_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
