# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20180321_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='units',
        ),
        migrations.AddField(
            model_name='departments',
            name='units',
            field=models.ManyToManyField(related_name='departmentsUnits', to='organization.Units'),
        ),
    ]
