# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20180321_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='division',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='unit',
        ),
    ]
