# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20180328_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='organization.Units'),
        ),
    ]
