# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_units_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='parents',
        ),
        migrations.AddField(
            model_name='units',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.Units'),
        ),
    ]
