# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='department',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='role',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
