# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20180629_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('firstnane', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('resume', models.FileField(null=True, upload_to=organization.models.getDepartmentsLogoAttachmentPath)),
                ('coverletter', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Screening', 'Screening'), ('SelfAssesmenent', 'SelfAssesmenent'), ('Interviewing', 'Interviewing'), ('Shortlisted', 'Shortlisted'), ('Negotiation', 'Negotiation'), ('Onboarding', 'Onboarding'), ('Closed', 'Closed')], default='Created', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Active', 'Active'), ('Closed', 'Closed')], default='Created', max_length=15),
        ),
    ]
