# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20180629_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='status',
        ),
    ]
