# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_auto_20180629_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Active', 'Active'), ('Closed', 'Closed')], default='Created', max_length=15),
        ),
    ]
