# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20180629_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='firstnane',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_applied', to='recruitment.Jobs'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='coverletter',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Screening', 'Screening'), ('SelfAssesmenent', 'SelfAssesmenent'), ('Interviewing', 'Interviewing'), ('Shortlisted', 'Shortlisted'), ('Negotiation', 'Negotiation'), ('Onboarding', 'Onboarding'), ('Closed', 'Closed')], default='Created', max_length=15),
        ),
    ]
