# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_auto_20180702_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='aggree',
            field=models.BooleanField(default=False),
        ),
    ]
