# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_jobapplication_aggree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Screening', 'Screening'), ('SelfAssesmenent', 'SelfAssesmenent'), ('TechInterviewing', 'TechInterviewing'), ('HrInterviewing', 'HrInterviewing'), ('Shortlisted', 'Shortlisted'), ('Negotiation', 'Negotiation'), ('Onboarding', 'Onboarding'), ('Closed', 'Closed')], default='Created', max_length=15),
        ),
    ]
