# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0013_auto_20180703_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True)),
                ('interviewDate', models.DateField()),
                ('slot', models.CharField(max_length=10, null=True)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('person', models.ManyToManyField(related_name='interviwer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
