# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_interview_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='person',
            new_name='interviewer',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='slot',
        ),
        migrations.AddField(
            model_name='interview',
            name='mode',
            field=models.CharField(choices=[('online', 'online'), ('telephonic', 'telephonic'), ('face-to-face', 'face-to-face')], default='online', max_length=15),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('suitable', 'suitable'), ('un-suitable', 'un-suitable'), ('recommand-other-job', 'recommand-other-job')], default='created', max_length=15),
        ),
    ]
