# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_auto_20180705_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
