# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_auto_20180705_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='recruitment.JobApplication'),
        ),
    ]
