# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 10:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0022_auto_20180705_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='interviewer',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviwer', to=settings.AUTH_USER_MODEL),
        ),
    ]
