# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0026_auto_20180706_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Screening', 'Screening'), ('Self-Assesmenent', 'SelfAssesmenent'), ('Techical-Interview', 'Techical-Interviewing'), ('HRInterview', 'HRInterview'), ('Shortlisted', 'Shortlisted'), ('Negotiation', 'Negotiation'), ('Onboarding', 'Onboarding'), ('Closed', 'Closed')], default='Created', max_length=15),
        ),
    ]
