# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0029_auto_20180709_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='dateOfJoin',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='sallary',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='dateOfJoin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='sallary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
