# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0030_auto_20180709_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='dateOfJoin',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='sallary',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='adHoc',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='adHocLeaves',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='al',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='basic',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hra',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='joiningDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='lta',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ml',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='notice',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='probation',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='special',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='taxSlab',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
