# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0031_auto_20180711_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='off',
            field=models.BooleanField(default=True),
        ),
    ]
