# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0032_jobapplication_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='notice',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='probation',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
