# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0033_auto_20180711_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='noticePeriodRecovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='probationNotice',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
