# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0034_auto_20180711_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='adHoc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='adHocLeaves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='al',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='basic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='hra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='lta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ml',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='probation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='probationNotice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='special',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='taxSlab',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
