# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0008_auto_20161017_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approvalMatrix', models.PositiveSmallIntegerField(default=1)),
                ('approvalStage', models.PositiveSmallIntegerField(default=0)),
                ('dispensed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=5)),
                ('dated', models.DateTimeField()),
                ('attachment', models.FileField(null=True, upload_to=finance.models.getInvoicesPath)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.service')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ExpenseSheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceGeneratedOrSubmitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fromAcc', models.PositiveIntegerField()),
                ('fromIFSC', models.CharField(max_length=10)),
                ('toAcc', models.PositiveIntegerField()),
                ('toIFSC', models.CharField(max_length=10)),
                ('ammount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expensesheet',
            name='settlement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Transaction'),
        ),
        migrations.AddField(
            model_name='expensesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseGeneratedOrSubmitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
