# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesheet',
            name='approvalMatrix',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='approvalStage',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='dispensed',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='transaction',
        ),
    ]
