# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20180309_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project'),
        ),
    ]
