# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20160522_0311'),
        ('finance', '0002_auto_20161122_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField()),
                ('ifsc', models.CharField(max_length=15)),
                ('bank', models.CharField(max_length=50)),
                ('bankAddress', models.TextField(max_length=500)),
                ('authorizedSignaturies', models.ManyToManyField(related_name='checkingAccounts', to=settings.AUTH_USER_MODEL)),
                ('contactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountsManaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='costCenters', to='projects.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='settlement',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fromIFSC',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='toIFSC',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fromAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='finance.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='toAcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='finance.Account'),
        ),
        migrations.DeleteModel(
            name='ExpenseSheet',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
