# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expensesheet_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
