# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20180309_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesheet',
            name='notes',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
