# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesheet',
            name='settled',
        ),
    ]
