# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_expensesheet_settled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dated',
            field=models.DateField(),
        ),
    ]
