# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20180310_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesheet',
            name='notes',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
