# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20161202_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(default='a desc text', max_length=200),
            preserve_default=False,
        ),
    ]
