# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20180310_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesheet',
            name='approvalMatrix',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='approvalStage',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='created',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='dispensed',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='expensesheet',
            name='user',
        ),
        migrations.AlterField(
            model_name='expensesheet',
            name='notes',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
