# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoice_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='apiCallParams',
            field=models.CharField(default=datetime.datetime(2017, 2, 8, 8, 45, 14, 382000, tzinfo=utc), max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='externalConfirmationID',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='externalReferenceID',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
    ]
