# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoice_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesheet',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
