# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20180310_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesheet',
            name='project',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExpenseSheet',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
