# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('ERP', '0002_auto_20170912_2011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0010_auto_20180310_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=30, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseGeneratedOrSubmitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=5)),
                ('dated', models.DateField()),
                ('attachment', models.FileField(null=True, upload_to=finance.models.getInvoicesPath)),
                ('description', models.TextField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.service')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.ExpenseSheet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceGeneratedOrSubmitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
