# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_inflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='balance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
