# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_expensesheet_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='approved',
        ),
    ]
