# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_expensesheet_submitted'),
        ('finance', '0012_inflow_balance'),
    ]

    operations = [
    ]
