# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_invoice_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sheet',
        ),
    ]
