# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_merge_20170327_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='personal',
            field=models.BooleanField(default=False),
        ),
    ]
