# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_invoice_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sheet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.ExpenseSheet'),
            preserve_default=False,
        ),
    ]
