# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_expensesheet_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
