# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20180312_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesheet',
            name='approved',
            field=models.CharField(default='approved', max_length=30, null=True),
        ),
    ]
