# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_invoice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesheet',
            name='approved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Pending', 'Pending')], default='No', max_length=5),
        ),
    ]
