# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('typ', models.CharField(choices=[('national', 'national'), ('state', 'state'), ('restricted', 'restricted')], default='national', max_length=20)),
            ],
        ),
    ]
