# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
