# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20170912_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='ERP.application'),
        ),
    ]
