# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20180319_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='ERP.module'),
        ),
    ]
