# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0003_companyholidays_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contactPerson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicesContactPerson', to=settings.AUTH_USER_MODEL),
        ),
    ]
