# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0007_address_media_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Doc',
            new_name='doc',
        ),
    ]
