# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 12:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0008_auto_20161017_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('month', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PublicApiKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('usageRemaining', models.PositiveIntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiKeyAdministrator', to=settings.AUTH_USER_MODEL)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicApiKeysOwned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apiusage',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='ERP.PublicApiKeys'),
        ),
    ]
