# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0009_auto_20170320_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='web',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
