# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_service_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='about',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.address'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mobile',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
