# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0013_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettingsfield',
            name='value',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
