# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutors24Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('school', models.CharField(choices=[('S', 'School'), ('C', 'College')], default='S', max_length=10, null=True)),
                ('schoolName', models.CharField(max_length=100, null=True)),
                ('standard', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12'), ('13', 'Class 13'), ('14', 'Class 14'), ('15', 'Class 15')], default='1', max_length=10, null=True)),
                ('street', models.TextField(max_length=100, null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('pinCode', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('balance', models.IntegerField(null=True)),
                ('typ', models.CharField(choices=[('S', 'Student'), ('T', 'Tutor')], default='S', max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
