# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20180326_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
