# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0005_auto_20180327_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(null=True, upload_to=tutor.models.getMessageAttachmentPath)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSession', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionMessage', to='tutor.Session')),
            ],
        ),
    ]
