# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='MSG',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
