# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20180327_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors24profile',
            name='parentEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tutors24profile',
            name='parentMobile',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
