# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20180328_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorSession', to=settings.AUTH_USER_MODEL),
        ),
    ]
