# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_auto_20180329_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
