# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_remove_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors24profile',
            name='balance',
            field=models.IntegerField(default=60),
        ),
    ]
