# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tutor.models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_auto_20180330_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=tutor.models.getImageUploadPath)),
                ('sessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessionId', to='tutor.Session')),
            ],
        ),
    ]
