# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_sessionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionimage',
            name='sessionID',
        ),
    ]
