# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldType', models.CharField(choices=[('char', 'char'), ('boolean', 'boolean'), ('float', 'float'), ('date', 'date'), ('choice', 'choice')], default='char', max_length=15)),
                ('unit', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('helpText', models.CharField(blank=True, max_length=100)),
                ('default', models.CharField(blank=True, max_length=100)),
                ('data', models.CharField(blank=True, max_length=30000)),
            ],
        ),
    ]
