# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
