# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20180522_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='listings', to='ecommerce.media'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
    ]
