# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0007_auto_20180523_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=ecommerce.models.getEcommerceBannerUploadPath)),
                ('title', models.CharField(max_length=20, null=True)),
                ('subtitle', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('params', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
