# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 05:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0053_auto_20180519_1046'),
        ('ecommerce', '0009_genericproduct_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtymap', models.CharField(max_length=20, null=True)),
                ('typ', models.CharField(choices=[('onlineVideo', 'onlineVideo'), ('video', 'video')], default='onlineVideo', max_length=10)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
