# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qtymap',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
