# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20180629_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qtymap',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='typ',
            field=models.CharField(choices=[('cart', 'cart'), ('favourite', 'favourite')], default='cart', max_length=10),
        ),
    ]
