# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-04 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100, null=True)),
                ('typ', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='dfs',
            field=models.ManyToManyField(blank=True, to='ecommerce.DataField'),
        ),
    ]
