# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 05:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0017_auto_20180704_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('cart', 'cart'), ('favourite', 'favourite')], default='loggedIn', max_length=10)),
                ('data', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerceActivities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
