# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='typ',
            field=models.CharField(choices=[('productView', 'productView'), ('categoryView', 'categoryView'), ('checkingOut', 'checkingOut'), ('loggedIn', 'loggedIn'), ('productCmmts', 'productCmmts'), ('removeFromCart', 'removeFromCart'), ('pageView', 'pageView')], default='loggedIn', max_length=10),
        ),
    ]
