# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_offerbanner_imageportrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
