# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-09 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_activities_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.listing'),
        ),
    ]
