# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
