# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_address_title'),
        ('ecommerce', '0022_activities_product'),
    ]

    operations = [
    ]
