# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0024_merge_20180710_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('totalAmount', models.PositiveIntegerField(blank=True, null=True)),
                ('paymentMode', models.CharField(choices=[('COD', 'COD'), ('card', 'card'), ('cash', 'cash')], max_length=10)),
                ('paymentRefId', models.CharField(blank=True, max_length=100, null=True)),
                ('paymentChannel', models.CharField(blank=True, max_length=100, null=True)),
                ('modeOfShopping', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=10)),
                ('paidAmount', models.PositiveIntegerField(blank=True, null=True)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('promoCode', models.CharField(blank=True, max_length=100, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'created'), ('failed', 'failed'), ('ordered', 'ordered'), ('completed', 'completed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderQtyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('totalAmount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('packed', 'packed'), ('shipped', 'shipped'), ('inTransit', 'inTransit'), ('reachedNearestHub', 'reachedNearestHub'), ('outForDelivery', 'outForDelivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returnToOrigin', 'returnToOrigin'), ('returned', 'returned')], max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('refundAmount', models.PositiveIntegerField(blank=True, null=True)),
                ('discountAmount', models.PositiveIntegerField(blank=True, null=True)),
                ('toBeRefunded', models.PositiveIntegerField(blank=True, null=True)),
                ('cancellable', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.listing')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logTxt', models.CharField(max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='orderqtymap',
            name='trackingLog',
            field=models.ManyToManyField(blank=True, related_name='orderTrackLog', to='ecommerce.TrackingLog'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderQtyMap',
            field=models.ManyToManyField(blank=True, related_name='orderQty', to='ecommerce.OrderQtyMap'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
