# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderqtymap',
            name='toBeRefunded',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='landMark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='orderqtymap',
            name='refundStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderQtyMap',
            field=models.ManyToManyField(blank=True, related_name='order', to='ecommerce.OrderQtyMap'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paidAmount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderqtymap',
            name='refundAmount',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderqtymap',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('packed', 'packed'), ('shipped', 'shipped'), ('inTransit', 'inTransit'), ('reachedNearestHub', 'reachedNearestHub'), ('outForDelivery', 'outForDelivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('returnToOrigin', 'returnToOrigin'), ('returned', 'returned')], default='created', max_length=10),
        ),
    ]
