# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_frequentlyquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentlyquestions',
            old_name='Ans',
            new_name='ans',
        ),
    ]
