# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_auto_20180712_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('failed', 'failed'), ('ordered', 'ordered'), ('completed', 'completed')], default='created', max_length=10),
        ),
    ]
