# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_auto_20180717_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqtymap',
            name='courierAWBNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderqtymap',
            name='courierName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderqtymap',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
