# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_auto_20180717_0702'),
        ('ecommerce', '0031_auto_20180717_0547'),
    ]

    operations = [
    ]
