# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0032_merge_20180718_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField()),
                ('textVal', models.CharField(max_length=1000, unique=True)),
                ('headingVal', models.CharField(max_length=100, unique=True)),
                ('productDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.listing')),
                ('userDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
