# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0033_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='userDetail',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ecommerceUser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
