# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_auto_20180801_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='productDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ecommerce.listing'),
        ),
    ]
