# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0037_auto_20180802_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=35, null=True)),
                ('mobile', models.CharField(max_length=14)),
                ('message', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supportUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
