# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_supportfeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportfeed',
            name='email',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
