# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='address',
        ),
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP.address'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='ERP.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP.address'),
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
