# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0049_auto_20170723_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericproduct',
            name='visual',
            field=models.ImageField(null=True, upload_to=ecommerce.models.getEcommerceProductVisualUploadPath),
        ),
    ]
