# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0050_auto_20170723_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericproduct',
            name='minCost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
