# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20180123_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10000, null=True)),
                ('value', models.PositiveIntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('quoted', 'quoted'), ('approved', 'approved'), ('billed', 'billed'), ('received', 'received'), ('dueElapsed', 'dueElapsed')], default='quoted', max_length=12)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='warehouse.Contract')),
            ],
        ),
    ]
