# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('quoted', 'quoted'), ('cancelled', 'cancelled'), ('approved', 'approved'), ('billed', 'billed'), ('received', 'received'), ('dueElapsed', 'dueElapsed')], default='quoted', max_length=12),
        ),
    ]
