# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_auto_20180219_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='occupancy_screenshort',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
