# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_contract_occupancy_screenshort'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contract',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ManyToManyField(related_name='invoices', to='warehouse.Contract'),
        ),
    ]
