# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20180226_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='contract',
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='warehouse.Contract'),
            preserve_default=False,
        ),
    ]
