# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='qty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
