# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0015_auto_20180319_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('typ', models.CharField(choices=[('qty', 'qty'), ('percent', 'percent')], default='qty', max_length=10)),
                ('initial', models.FloatField()),
                ('value', models.FloatField()),
                ('final', models.FloatField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='warehouse.Checkin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wareHouseCheckouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
