# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='qty',
            field=models.FloatField(null=True),
        ),
    ]
