# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_checkin_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='awb',
            field=models.FileField(null=True, upload_to=warehouse.models.checkinUploadPath),
        ),
    ]
