# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_checkin_awb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='occupancy_screenshort',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
