# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0021_auto_20180710_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='grandTotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
