# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitweb', '0022_auto_20160521_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='device',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
