# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 05:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_auto_20180424_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=100, null=True)),
                ('refurbished', models.BooleanField(default=False)),
                ('returned', models.BooleanField(default=False)),
                ('returnComment', models.CharField(max_length=200, null=True)),
                ('approvedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvedBy', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='assets.Asset')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetsAlloted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allotment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNos', models.CharField(max_length=500, null=True)),
                ('warrantyTill', models.DateField(null=True)),
                ('manufacturedOn', models.DateField(null=True)),
                ('qty', models.PositiveIntegerField(null=True)),
                ('poNumber', models.PositiveIntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='assets.Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetsCheckedIn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
