# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180424_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='modelNo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
