# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20180424_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
