# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_checkout_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='serialNo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='sentTo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
