# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 17:58
from __future__ import unicode_literals

import clientRelationships.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('typ', models.CharField(choices=[('call', 'call'), ('meeting', 'meeting'), ('mail', 'mail'), ('todo', 'todo'), ('note', 'note'), ('stateChange', 'stateChange')], default='call', max_length=11)),
                ('data', models.CharField(max_length=300)),
                ('notes', models.TextField(max_length=1000, null=True)),
                ('doc', models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipActivity)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('emailSecondary', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('mobileSecondary', models.CharField(max_length=12, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('notes', models.TextField(max_length=300, null=True)),
                ('linkedin', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('dp', models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipContactDP)),
                ('male', models.BooleanField(default=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ERP.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doc', models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipContract)),
                ('value', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('quoted', 'quoted'), ('approved', 'approved'), ('billed', 'billed'), ('received', 'received')], default='quoted', max_length=10)),
                ('details', models.TextField(max_length=10000, null=True)),
                ('data', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(default=0, null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=4)),
                ('state', models.CharField(choices=[('created', 'created'), ('contacted', 'contacted'), ('demo', 'demo'), ('requirements', 'requirements'), ('proposal', 'proposal'), ('negotiation', 'negotiation'), ('conclusion', 'conclusion')], default='created', max_length=13)),
                ('requirements', models.TextField(max_length=10000, null=True)),
                ('probability', models.SmallIntegerField(default=100)),
                ('closeDate', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('result', models.CharField(choices=[('na', 'na'), ('won', 'won'), ('lost', 'lost')], default='na', max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='ERP.service')),
                ('contacts', models.ManyToManyField(blank=True, related_name='deals', to='clientRelationships.Contact')),
                ('internalUsers', models.ManyToManyField(blank=True, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealsCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clientRelationships.Deal'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clientRelationships.Contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='activitiesMentioned', to='clientRelationships.Contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clientRelationships.Deal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='internalUsers',
            field=models.ManyToManyField(blank=True, related_name='activitiesMentioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
