# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0010_service_web'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('emailSecondary', models.EmailField(max_length=254, null=True)),
                ('mobile', models.PositiveSmallIntegerField()),
                ('mobileSecondary', models.PositiveSmallIntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('notes', models.TextField(max_length=300)),
                ('likedin', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ERP.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doc', models.FileField(upload_to='')),
                ('value', models.PositiveIntegerField()),
                ('relationType', models.CharField(choices=[('onetime', 'onetime'), ('request', 'request'), ('days', 'days'), ('hours', 'hours'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=4)),
                ('state', models.CharField(choices=[('created', 'created'), ('contacted', 'contacted'), ('demo', 'demo'), ('requirements', 'requirements'), ('proposal', 'proposal'), ('negotiation', 'negotiation'), ('won', 'won'), ('lost', 'lost')], max_length=13)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='ERP.service')),
                ('contact', models.ManyToManyField(to='clientRelationships.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientRelationships.Deal'),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
