# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-31 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='likedin',
            new_name='linkedin',
        ),
    ]
