# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='approvedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
