# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0002_auto_20171028_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='dueDate',
            field=models.DateField(null=True),
        ),
    ]
