# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0003_schedule_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='email',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='slot',
            field=models.CharField(choices=[('N/A', 'N/A'), ('1 AM', '1 AM'), ('2 AM', '2 AM'), ('3 AM', '3 AM'), ('4 AM', '4 AM'), ('5 AM', '5 AM'), ('6 AM', '6 AM'), ('7 AM', '7 AM'), ('8 AM', '8 AM'), ('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 AM', '12 AM'), ('13 PM', '13 PM'), ('14 PM', '14 PM'), ('15 PM', '15 PM'), ('16 PM', '16 PM'), ('17 PM', '17 PM'), ('18 PM', '18 PM'), ('19 PM', '19 PM'), ('20 PM', '20 PM'), ('21 PM', '21 PM'), ('22 PM', '22 PM'), ('23 PM', '23 PM'), ('24 PM', '24 PM')], default='N/A', max_length=11),
        ),
    ]
