# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 20:17
from __future__ import unicode_literals

import clientRelationships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0003_contract_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='doc',
        ),
        migrations.AddField(
            model_name='deal',
            name='doc',
            field=models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipContract),
        ),
    ]
