# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0004_auto_20170902_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobileSecondary',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deal',
            name='value',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
