# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0004_auto_20171028_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='duePenalty',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='rate',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
