# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 12:03
from __future__ import unicode_literals

import clientRelationships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0005_auto_20170902_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dp',
            field=models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipContactDP),
        ),
    ]
