# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0006_contact_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='male',
            field=models.BooleanField(default=True),
        ),
    ]
