# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0007_contact_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='typ',
            field=models.CharField(choices=[('call', 'call'), ('meeting', 'meeting'), ('onlineConf', 'onlineConf'), ('lunch', 'lunch'), ('mail', 'mail'), ('todo', 'todo'), ('note', 'note')], default='call', max_length=11),
        ),
    ]
