# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 08:14
from __future__ import unicode_literals

import clientRelationships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0008_auto_20170903_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='doc',
            field=models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipActivity),
        ),
    ]
