# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientRelationships', '0009_activity_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contacts',
            field=models.ManyToManyField(related_name='activitiesMentioned', to='clientRelationships.Contact'),
        ),
        migrations.AddField(
            model_name='activity',
            name='internalUsers',
            field=models.ManyToManyField(related_name='activitiesMentioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='typ',
            field=models.CharField(choices=[('call', 'call'), ('meeting', 'meeting'), ('mail', 'mail'), ('todo', 'todo'), ('note', 'note')], default='call', max_length=11),
        ),
    ]
