# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-04 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0010_auto_20170904_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='activitiesMentioned', to='clientRelationships.Contact'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='internalUsers',
            field=models.ManyToManyField(blank=True, related_name='activitiesMentioned', to=settings.AUTH_USER_MODEL),
        ),
    ]
