# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 20:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientRelationships', '0011_auto_20170904_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='contact',
        ),
        migrations.AddField(
            model_name='deal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='closeDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='contacts',
            field=models.ManyToManyField(related_name='deals', to='clientRelationships.Contact'),
        ),
        migrations.AddField(
            model_name='deal',
            name='internalUsers',
            field=models.ManyToManyField(related_name='deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.SmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='deal',
            name='requirements',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealsCreated', to=settings.AUTH_USER_MODEL),
        ),
    ]
