# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0012_auto_20170905_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='typ',
            field=models.CharField(choices=[('call', 'call'), ('meeting', 'meeting'), ('mail', 'mail'), ('todo', 'todo'), ('note', 'note'), ('stateChange', 'stateChange')], default='call', max_length=11),
        ),
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('contacted', 'contacted'), ('demo', 'demo'), ('requirements', 'requirements'), ('proposal', 'proposal'), ('negotiation', 'negotiation'), ('won', 'won')], max_length=13),
        ),
    ]
