# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0013_auto_20170906_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='deals', to='clientRelationships.Contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=4),
        ),
        migrations.AlterField(
            model_name='deal',
            name='internalUsers',
            field=models.ManyToManyField(blank=True, related_name='deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('created', 'created'), ('contacted', 'contacted'), ('demo', 'demo'), ('requirements', 'requirements'), ('proposal', 'proposal'), ('negotiation', 'negotiation'), ('won', 'won')], default='created', max_length=13),
        ),
    ]
