# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0014_auto_20170906_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='relation',
            field=models.CharField(choices=[('onetime', 'onetime'), ('request', 'request'), ('days', 'days'), ('hours', 'hours'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='onetime', max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='closeDate',
            field=models.DateTimeField(null=True),
        ),
    ]
