# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0015_auto_20170906_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='name',
            field=models.CharField(default='old name', max_length=100),
            preserve_default=False,
        ),
    ]
