# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0018_deal_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='relationType',
            field=models.CharField(choices=[('onetime', 'onetime'), ('request', 'request'), ('day', 'day'), ('hour', 'hour'), ('monthly', 'monthly'), ('yearly', 'yearly')], max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='relation',
            field=models.CharField(choices=[('onetime', 'onetime'), ('request', 'request'), ('day', 'day'), ('hour', 'hour'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='onetime', max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='result',
            field=models.CharField(choices=[('na', 'na'), ('won', 'won'), ('lost', 'lost')], default='na', max_length=4),
        ),
    ]
