# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0019_auto_20170909_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='requirements',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
