# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0020_auto_20170909_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='requirements',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
