# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0021_auto_20170909_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='relationType',
        ),
        migrations.AddField(
            model_name='contract',
            name='details',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('quoted', 'quoted'), ('approved', 'approved'), ('billed', 'billed'), ('received', 'received')], default='quoted', max_length=10),
        ),
    ]
