# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0022_auto_20170909_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='relation',
        ),
        migrations.AddField(
            model_name='contract',
            name='data',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='relation',
            field=models.CharField(choices=[('onetime', 'onetime'), ('request', 'request'), ('day', 'day'), ('hour', 'hour'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='onetime', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='clientRelationships.Deal'),
        ),
    ]
