# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 16:56
from __future__ import unicode_literals

import clientRelationships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0023_auto_20170910_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='data',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='details',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='doc',
            field=models.FileField(null=True, upload_to=clientRelationships.models.getClientRelationshipContract),
        ),
    ]
