# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0025_auto_20170910_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='relation',
        ),
    ]
