# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='unitType',
        ),
    ]
