# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20180501_1037'),
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField(null=True)),
                ('toDate', models.DateField(null=True)),
                ('days', models.PositiveIntegerField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[(b'AL', b'AL'), (b'ML', b'ML'), (b'casual', b'casual')], max_length=100)),
                ('comment', models.CharField(max_length=10000, null=True)),
                ('approvedStage', models.PositiveIntegerField(default=0, null=True)),
                ('approvedMatrix', models.PositiveIntegerField(default=1, null=True)),
                ('approvedBy', models.ManyToManyField(blank=True, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.Departments'),
        ),
        migrations.AddField(
            model_name='designation',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.Division'),
        ),
        migrations.AddField(
            model_name='designation',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.Role'),
        ),
        migrations.AddField(
            model_name='designation',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.Unit'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='PFUan',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
