# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='PFUan',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
