# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20180309_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='domain',
            field=models.CharField(choices=[(b'Not selected..', b'Not selected..'), (b'Automotive', b'Automotive'), (b'Service', b'Service'), (b'University', b'University'), (b'FMCG', b'FMCG'), (b'Power', b'Power'), (b'Pharmaceuticals', b'Pharmaceuticals'), (b'Manufacturing', b'Manufacturing'), (b'Tele Communications', b'Tele Communications')], default=b'Not selected..', max_length=15),
        ),
        migrations.AddField(
            model_name='designation',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HR.rank'),
        ),
        migrations.AddField(
            model_name='designation',
            name='unit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='unitType',
            field=models.CharField(choices=[(b'Not selected..', b'Not selected..'), (b'Research and Development', b'Research and Development'), (b'Operations', b'Operations'), (b'Management', b'Management')], default=b'Not selected..', max_length=30),
        ),
    ]
