# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0002_auto_20180528_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField(null=True)),
                ('toDate', models.DateField(null=True)),
                ('days', models.PositiveIntegerField(null=True)),
                ('approved', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[(b'AL', b'AL'), (b'ML', b'ML'), (b'casual', b'casual')], max_length=100)),
                ('comment', models.CharField(max_length=10000, null=True)),
                ('approvedStage', models.PositiveIntegerField(default=0, null=True)),
                ('approvedMatrix', models.PositiveIntegerField(default=1, null=True)),
                ('approvedBy', models.ManyToManyField(blank=True, related_name='leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leavesAuthored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
