# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0002_auto_20180501_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leavesAuthored', to=settings.AUTH_USER_MODEL),
        ),
    ]
