# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='adHocLeavesHold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='alHold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='mlHold',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
