# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-22 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_auto_20160824_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountskey',
            name='keyType',
            field=models.CharField(choices=[(b'hashed', b'hashed'), (b'otp', b'otp')], default=b'hashed', max_length=6),
        ),
    ]
