# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_auto_20180531_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[(b'inProcess', b'inProcess'), (b'approved', b'approved'), (b'rejected', b'rejected')], default=b'inProcess', max_length=100),
        ),
    ]
