# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_auto_20180307_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='ifscCode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
