# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='takenLeaves',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
