# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR', '0005_accountskey_keytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=400)),
                ('issuedTo', models.CharField(max_length=400)),
                ('passKey', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=25)),
                ('issuedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificatesIssued', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
