# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.CharField(max_length=35),
        ),
    ]
