# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_auto_20180312_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='accountNumber',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='noticePeriodRecovery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='off',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='policyNumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
