# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_auto_20170731_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='app',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='docID',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
