# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_auto_20180531_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='adHocLeavesHold',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='alHold',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='mlHold',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
