# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_auto_20180313_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='deboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payroll',
            name='lastWorkingDate',
            field=models.DateField(null=True),
        ),
    ]
