# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0008_auto_20180531_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
