# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_auto_20180313_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='joiningDate',
            field=models.DateField(null=True),
        ),
    ]
