# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_auto_20180310_1623'),
        ('HR', '0010_auto_20180314_0613'),
    ]

    operations = [
    ]
