# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_auto_20180601_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='adHocLeavesHold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='alHold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='mlHold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
