# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0011_merge_20180321_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
