# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_auto_20180321_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='primaryApprover',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='reportingTo',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='secondaryApprover',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='user',
        ),
        migrations.DeleteModel(
            name='designation',
        ),
    ]
