# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_address'),
        ('HR', '0014_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(to='ecommerce.Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='primaryAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaryAddress', to='ecommerce.Address'),
        ),
    ]
