# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:05
from __future__ import unicode_literals

import HR.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0015_payroll_taxslab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='empID',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tele',
        ),
        migrations.AddField(
            model_name='profile',
            name='appointmentAcceptance',
            field=models.FileField(blank=True, null=True, upload_to=HR.models.getAppointmentAcceptanceDocsPath),
        ),
        migrations.AddField(
            model_name='profile',
            name='bloodGroup',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cheque',
            field=models.FileField(blank=True, null=True, upload_to=HR.models.getChequeDocsPath),
        ),
        migrations.AddField(
            model_name='profile',
            name='drivingLicense',
            field=models.FileField(blank=True, null=True, upload_to=HR.models.getDrivingLicenseDocsPath),
        ),
        migrations.AddField(
            model_name='profile',
            name='married',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to=HR.models.getPANDocsPath),
        ),
        migrations.AddField(
            model_name='profile',
            name='passbook',
            field=models.FileField(blank=True, null=True, upload_to=HR.models.getPassbookDocsPath),
        ),
        migrations.AddField(
            model_name='profile',
            name='resignation',
            field=models.FileField(blank=True, null=True, upload_to=HR.models.getResignationDocsPath),
        ),
        migrations.AddField(
            model_name='profile',
            name='sameAsLocal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicleRegistration',
            field=models.FileField(blank=True, null=True, upload_to=HR.models.getVehicleRegDocsPath),
        ),
        migrations.AlterField(
            model_name='profile',
            name='IDPhoto',
            field=models.FileField(null=True, upload_to=HR.models.getDisplayPicturePath),
        ),
        migrations.AlterField(
            model_name='profile',
            name='emergency',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[(b'NA', b'NA'), (b'Kumar', b'Kumar'), (b'Kumari', b'Kumari'), (b'Smt', b'Smt'), (b'Shri', b'Shri'), (b'Dr', b'Dr')], default=b'NA', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sign',
            field=models.FileField(null=True, upload_to=HR.models.getSignaturesPath),
        ),
    ]
