# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0016_auto_20180412_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empID',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
