# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0017_profile_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sameAsLocal',
        ),
        migrations.AddField(
            model_name='profile',
            name='sameAsShipping',
            field=models.BooleanField(default=False),
        ),
    ]
