# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0018_auto_20180412_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sameAsShipping',
            field=models.BooleanField(default=True),
        ),
    ]
