# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0019_auto_20180412_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sameAsShipping',
            field=models.BooleanField(default=False),
        ),
    ]
