# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0021_auto_20180413_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='PFUan',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pan',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
