# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0022_auto_20180414_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='pan',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
