# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20180414_1256'),
        ('HR', '0023_auto_20180414_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.Departments'),
        ),
        migrations.AddField(
            model_name='designation',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.Division'),
        ),
        migrations.AddField(
            model_name='designation',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.Role'),
        ),
        migrations.AddField(
            model_name='designation',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.Unit'),
        ),
    ]
