# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 04:15
from __future__ import unicode_literals

import PIM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0003_auto_20170928_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ogimage',
            field=models.FileField(null=True, upload_to=PIM.models.getOGImageAttachment),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ogimageUrl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
