# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0004_calendar_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='data',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
