# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0004_auto_20180401_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='url',
            new_name='shortUrl',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tagsCSV',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='PIM.blogCategory'),
        ),
    ]
