# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 08:45
from __future__ import unicode_literals

import PIM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0005_auto_20180401_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='ogimage',
            field=models.ImageField(null=True, upload_to=PIM.models.getOGImageAttachment),
        ),
    ]
