# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIM', '0006_auto_20180401_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='contentType',
            field=models.CharField(choices=[(b'article', b'article'), (b'tutorial', b'tutorial'), (b'whitepaper', b'whitepaper'), (b'product', b'product'), (b'book', b'book'), (b'question', b'question')], default=b'article', max_length=15),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='shortUrl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
