# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_contacts_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('filterFrom', models.DateField(blank=True, null=True)),
                ('filterTo', models.DateField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='marketing.Tag')),
            ],
        ),
    ]
