# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('started', 'started'), ('closed', 'closed')], default='created', max_length=15),
        ),
    ]
