# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_campaign_particpents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='particpents',
            new_name='participants',
        ),
    ]
