# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_auto_20180608_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='directions',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='emailBody',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='emailSubject',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='msgBody',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
