# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_auto_20180608_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
