# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 04:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('approvedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managingTime', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeSheetCreated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField()),
                ('comment', models.CharField(max_length=10000, null=True)),
                ('approvalComment', models.CharField(max_length=10000, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='performance.TimeSheet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectsTime', to='projects.project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set([('user', 'date')]),
        ),
    ]
