# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
