# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 05:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20180503_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='approvedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managingTime', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeSheetCreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='performance.TimeSheet'),
        ),
    ]
