# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20180503_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='performance.TimeSheet'),
        ),
        migrations.AlterField(
            model_name='timesheetitem',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectsTime', to='projects.project'),
        ),
    ]
