# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_timesheetitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetitem',
            name='status',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('saved', 'saved'), ('submitted', 'submitted'), ('approved', 'approved')], default='created', max_length=10, null=True),
        ),
    ]
