# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0006_auto_20180503_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='approvedBy',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approvedBy',
            field=models.ManyToManyField(blank=True, related_name='sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
