# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20180503_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='approvedBy',
            field=models.ManyToManyField(blank=True, related_name='times', to=settings.AUTH_USER_MODEL),
        ),
    ]
