# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_auto_20180503_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='checkIn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='checkOut',
            field=models.DateTimeField(null=True),
        ),
    ]
