# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ERP', '0005_service_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chat', models.BooleanField(default=False)),
                ('call', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('videoAndAudio', models.BooleanField(default=False)),
                ('vr', models.BooleanField(default=False)),
                ('windowColor', models.CharField(max_length=20, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerProfile', to='ERP.service')),
            ],
        ),
    ]
