# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
