# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180325_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryAndContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
