# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 13:37
from __future__ import unicode_literals

import POS.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientRelationships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('notes', models.TextField(max_length=10000, null=True)),
                ('pan', models.CharField(max_length=100, null=True)),
                ('gst', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('sameAsShipping', models.BooleanField(default=False)),
                ('streetBilling', models.CharField(max_length=100, null=True)),
                ('cityBilling', models.CharField(max_length=100, null=True)),
                ('stateBilling', models.CharField(max_length=100, null=True)),
                ('pincodeBilling', models.CharField(max_length=100, null=True)),
                ('countryBilling', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posContacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('marketPlace', models.CharField(max_length=50, null=True)),
                ('orderID', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('packed', 'packed'), ('shipped', 'shipped'), ('recieved', 'recieved'), ('paid', 'paid'), ('reconciled', 'reconciled'), ('cancelled', 'cancelled'), ('rto', 'rto'), ('returned', 'returned')], default='new', max_length=10)),
                ('buyersPrice', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('shipper', models.CharField(max_length=100, null=True)),
                ('shipperAWB', models.CharField(max_length=100, null=True)),
                ('shippingFees', models.FloatField(null=True)),
                ('shippingTax', models.FloatField(null=True)),
                ('marketPlaceTax', models.FloatField(null=True)),
                ('earnings', models.FloatField(null=True)),
                ('buyerPincode', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrdersQtyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serialNumber', models.CharField(max_length=100, null=True)),
                ('invoicedate', models.DateField(null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('duedate', models.DateField(null=True)),
                ('returnquater', models.CharField(choices=[('jan-march', 'jan-march'), ('april-june', 'april-june'), ('july-sep', 'july-sep'), ('oct-dec', 'oct-dec')], max_length=10, null=True)),
                ('products', models.CharField(max_length=10000, null=True)),
                ('amountRecieved', models.PositiveIntegerField(default=0)),
                ('modeOfPayment', models.CharField(choices=[('card', 'card'), ('netBanking', 'netBanking'), ('cash', 'cash'), ('cheque', 'cheque'), ('wallet', 'wallet')], max_length=10, null=True)),
                ('received', models.BooleanField(default=True)),
                ('grandTotal', models.FloatField()),
                ('totalTax', models.FloatField()),
                ('paymentRefNum', models.PositiveIntegerField(default=0)),
                ('receivedDate', models.DateField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('displayPicture', models.ImageField(null=True, upload_to=POS.models.getPOSProductUploadPath)),
                ('serialNo', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(max_length=10000, null=True)),
                ('inStock', models.IntegerField(default=0)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('logistics', models.PositiveIntegerField(default=0)),
                ('serialId', models.CharField(max_length=50, null=True)),
                ('reorderTrashold', models.PositiveIntegerField(default=0)),
                ('productMeta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POSProducts', to='clientRelationships.ProductMeta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posProducts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMetaList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('code', models.PositiveIntegerField(default=0)),
                ('taxRate', models.PositiveIntegerField(default=0)),
                ('hsn', models.BooleanField(default=True)),
                ('sac', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productMetaList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVerient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=10000, null=True)),
                ('unitPerpack', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentProducts', to='POS.Product')),
            ],
        ),
        migrations.AddField(
            model_name='externalordersqtymap',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalOrders', to='POS.Product'),
        ),
        migrations.AddField(
            model_name='externalorders',
            name='products',
            field=models.ManyToManyField(to='POS.ExternalOrdersQtyMap'),
        ),
    ]
