# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 04:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('notes', models.TextField(max_length=300, null=True)),
                ('pan', models.CharField(max_length=100, null=True)),
                ('gst', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('sameAsShipping', models.BooleanField(default=False)),
                ('streetBilling', models.CharField(max_length=100, null=True)),
                ('cityBilling', models.CharField(max_length=100, null=True)),
                ('stateBilling', models.CharField(max_length=100, null=True)),
                ('pincodeBilling', models.CharField(max_length=100, null=True)),
                ('countryBilling', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posContacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
