# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Customer',
        ),
    ]
