# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serialNo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
