# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_auto_20180120_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
