# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0005_auto_20180120_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('hsnCode', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('displayPicture', models.ImageField(null=True, upload_to=b'')),
                ('serialNo', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('inStock', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posProducts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
