# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 08:47
from __future__ import unicode_literals

import POS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='displayPicture',
            field=models.ImageField(null=True, upload_to=POS.models.getPOSProductUploadPath),
        ),
    ]
