# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientRelationships', '0008_contract_grandtotal'),
        ('POS', '0007_auto_20180120_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hsnCode',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='logistics',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='productMeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='POSProducts', to='clientRelationships.ProductMeta'),
        ),
    ]
