# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0008_auto_20180131_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='serialNo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
