# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0009_auto_20180131_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='itemType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
