# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0010_auto_20180131_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('serialNumber', models.CharField(max_length=100, null=True)),
                ('invoicedate', models.DateField(null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('duedate', models.DateField(null=True)),
                ('returndate', models.DateField(null=True)),
                ('returnquater', models.DateField(null=True)),
                ('product', models.CharField(max_length=1000, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='POS.Customer')),
            ],
        ),
    ]
