# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0011_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
