# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0012_auto_20180202_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='duedate',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoicedate',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
