# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0013_auto_20180203_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='duedate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoicedate',
            field=models.DateField(null=True),
        ),
    ]
