# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0014_auto_20180203_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='duedate',
            new_name='dates',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoicedate',
            new_name='deuDate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='returndate',
            new_name='invoiceDate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='returnquater',
            new_name='returndates',
        ),
    ]
