# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-03 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0015_auto_20180203_0528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='dates',
            new_name='duedate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='deuDate',
            new_name='returndate',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='returndates',
            new_name='returnquater',
        ),
    ]
