# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0016_auto_20180203_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceDate',
            new_name='invoicedate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amountRecieved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
