# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-17 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0018_invoice_modeofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='grandTotal',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='received',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='totalTax',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
