# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0019_auto_20180217_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paymentRefNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='modeOfPayment',
            field=models.CharField(choices=[('card', 'card'), ('netBanking', 'netBanking'), ('cash', 'cash'), ('cheque', 'cheque'), ('wallet', 'wallet')], max_length=10, null=True),
        ),
    ]
