# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0020_auto_20180218_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='returndate',
        ),
    ]
