# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0021_remove_invoice_returndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='returnquater',
            field=models.CharField(choices=[('jan-march', 'jan-march'), ('april-june', 'april-june'), ('july-sep', 'july-sep'), ('oct-dec', 'oct-dec')], max_length=10, null=True),
        ),
    ]
