# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0022_auto_20180218_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receivedDate',
            field=models.DateField(null=True),
        ),
    ]
