# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0024_auto_20180219_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
