# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0025_auto_20180219_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recordTrashold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='serialId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
