# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0025_auto_20180219_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='inStock',
            field=models.IntegerField(default=0),
        ),
    ]
