# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0026_auto_20180317_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('marketPlace', models.CharField(max_length=50, null=True)),
                ('orderID', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('packed', 'packed'), ('shipped', 'shipped'), ('recieved', 'recieved'), ('paid', 'paid'), ('reconciled', 'reconciled'), ('cancelled', 'cancelled'), ('rto', 'rto'), ('returned', 'returned')], default='new', max_length=10)),
                ('buyersPrice', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('shipper', models.CharField(max_length=100, null=True)),
                ('shipperAWB', models.CharField(max_length=100, null=True)),
                ('shippingFees', models.FloatField(null=True)),
                ('shippingTax', models.FloatField(null=True)),
                ('marketPlaceTax', models.FloatField(null=True)),
                ('earnings', models.FloatField(null=True)),
                ('buyerPincode', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrdersQtyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='externalOrders', to='POS.Product')),
            ],
        ),
        migrations.AddField(
            model_name='externalorders',
            name='products',
            field=models.ManyToManyField(to='POS.ExternalOrdersQtyMap'),
        ),
    ]
