# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0026_auto_20180322_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='recordTrashold',
            new_name='reorderTrashold',
        ),
    ]
