# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0027_auto_20180322_1441'),
        ('POS', '0027_auto_20180318_1322'),
    ]

    operations = [
    ]
