# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0028_merge_20180322_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVerient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=10000, null=True)),
                ('unitPerpack', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentProducts', to='POS.Product')),
            ],
        ),
    ]
