# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0028_merge_20180322_1539'),
        ('POS', '0028_merge_20180323_0327'),
    ]

    operations = [
    ]
