# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0032_productmetalist'),
        ('POS', '0028_merge_20180322_1539'),
        ('POS', '0028_merge_20180323_0327'),
    ]

    operations = [
    ]
