# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0029_merge_20180323_1745'),
        ('POS', '0032_productmetalist'),
    ]

    operations = [
    ]
