# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0033_merge_20180406_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('typ', models.CharField(choices=[('system', 'system'), ('user', 'user')], max_length=10, null=True)),
                ('before', models.PositiveIntegerField(default=0)),
                ('after', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryLogProduct', to='POS.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryLog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
