# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POS', '0034_inventorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='externalOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalOrders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventoryLog', to=settings.AUTH_USER_MODEL),
        ),
    ]
