# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0035_auto_20180407_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='externalOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalOrders', to='POS.ExternalOrders'),
        ),
    ]
