# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0037_auto_20180407_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentRefNum',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
