# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0038_auto_20180407_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorders',
            name='orderID',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
