# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 07:59
from __future__ import unicode_literals

import POS.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20180319_0720'),
        ('POS', '0038_auto_20180407_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contactDoc', models.FileField(null=True, upload_to=POS.models.getContractDoc)),
                ('paymentTerm', models.PositiveIntegerField(default=0)),
                ('contactPersonName', models.CharField(max_length=100)),
                ('contactPersonNumber', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ERP.service')),
            ],
        ),
        migrations.CreateModel(
            name='VendorServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('logistics', models.PositiveIntegerField(default=0)),
                ('fulfilmentTime', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendorsProduct', to='POS.Product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='POS.VendorProfile')),
            ],
        ),
    ]
