# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0039_vendorprofile_vendorservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ERP.service'),
        ),
        migrations.AlterField(
            model_name='vendorservices',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='POS.VendorProfile'),
        ),
    ]
