# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0040_auto_20180420_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorservices',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
