# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ERP', '0003_auto_20180319_0720'),
        ('POS', '0041_vendorservices_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseOrderDate', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=100)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('qty', models.PositiveIntegerField(default=6)),
                ('status', models.CharField(choices=[('create', 'create'), ('sent', 'sent'), ('returned', 'returned'), ('cancelled', 'cancelled')], max_length=10, null=True)),
                ('product', models.CharField(max_length=10000, null=True)),
                ('totalamount', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseServices', to='ERP.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
