# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0042_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchaseOrderDate',
        ),
    ]
