# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0043_remove_purchaseorder_purchaseorderdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='product',
            new_name='products',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rate',
        ),
    ]
