# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0044_auto_20180425_1317'),
        ('POS', '0039_auto_20180410_1034'),
    ]

    operations = [
    ]
