# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0046_remove_vendorservices_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('sent', 'sent'), ('returned', 'returned'), ('cancelled', 'cancelled')], default='created', max_length=10),
        ),
    ]
