# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0046_remove_vendorservices_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorders',
            name='orderID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
