# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0047_auto_20180514_1234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='externalorders',
            unique_together=set([('marketPlace', 'orderID')]),
        ),
    ]
