# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0048_vendorprofile_contactpersonemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('sent', 'sent'), ('returned', 'returned'), ('cancelled', 'cancelled'), ('recieved', 'recieved'), ('reconciled', 'reconciled')], default='created', max_length=10),
        ),
    ]
