# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0048_auto_20180514_1239'),
        ('POS', '0049_auto_20180428_1444'),
    ]

    operations = [
    ]
