# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0050_merge_20180515_1428'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorylog',
            unique_together=set([('externalOrder', 'product')]),
        ),
    ]
