# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0052_auto_20180519_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ERP.service'),
        ),
    ]
