# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0053_auto_20180519_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compositions',
            field=models.ManyToManyField(blank=True, related_name='_product_compositions_+', to='POS.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='haveComposition',
            field=models.BooleanField(default=False),
        ),
    ]
