# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-10 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0057_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
