# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0061_remove_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('netBanking', 'netBanking')], max_length=10, null=True),
        ),
    ]
