# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0062_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kilo Gram', 'Kilo Gram'), ('Gram', 'Gram'), ('Litre', 'Litre'), ('Quantity', 'Quantity')], max_length=10, null=True),
        ),
    ]
