# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0064_auto_20180724_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Ton', 'Ton'), ('Kilogram', 'Kilogram'), ('Gram', 'Gram'), ('Litre', 'Litre'), ('Millilitre', 'Millilitre'), ('Quantity', 'Quantity')], max_length=10, null=True),
        ),
    ]
