# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0065_auto_20180724_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='internalInvoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to='POS.Invoice'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='internalOrder',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
