# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-26 07:11
from __future__ import unicode_literals

import LMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('text', 'text'), ('image', 'image')], default='text', max_length=10)),
                ('txt', models.CharField(max_length=2000, null=True)),
                ('image', models.FileField(null=True, upload_to=LMS.models.getQAttachmentPath)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('ques', models.CharField(max_length=5000)),
                ('forReview', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('optionsParts', models.ManyToManyField(blank=True, related_name='questionsOptions', to='LMS.QPart')),
                ('quesParts', models.ManyToManyField(blank=True, related_name='questions', to='LMS.QPart')),
                ('solutionParts', models.ManyToManyField(blank=True, related_name='questionsSolutions', to='LMS.QPart')),
            ],
        ),
    ]
