# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:26
from __future__ import unicode_literals

import LMS.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('evaluated', models.BooleanField(default=False)),
                ('correct', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('partial', 'partial')], default='no', max_length=10)),
                ('marksObtained', models.PositiveIntegerField(default=0)),
                ('attachment', models.FileField(null=True, upload_to=LMS.models.getAnswerAttachmentPath)),
                ('txt', models.TextField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('txt', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('enrollmentStatus', models.CharField(choices=[('open', 'open'), ('onInvitation', 'onInvitation'), ('admin', 'admin'), ('onRequest', 'onRequest'), ('closed', 'closed')], default='pdf', max_length=20)),
                ('description', models.TextField(max_length=2000)),
                ('TAs', models.ManyToManyField(blank=True, related_name='lmsCourseAssisting', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lmsCoursesInstructing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('accepted', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lmsUsersAdded', to=settings.AUTH_USER_MODEL)),
                ('couse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='LMS.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('level', models.PositiveIntegerField(null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('typ', models.CharField(choices=[('pdf', 'pdf'), ('presentation', 'presentation'), ('word', 'word'), ('video', 'video'), ('image', 'image'), ('code', 'code'), ('zip', 'zip')], default='pdf', max_length=20)),
                ('attachment', models.FileField(null=True, upload_to=LMS.models.getStudyMaterialAttachmentPath)),
                ('archived', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('level', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='codeLang',
            field=models.CharField(choices=[('python', 'Python'), ('bash', 'Bash'), ('c', 'C Language'), ('cpp', 'C++ Language'), ('java', 'Java Language'), ('scilab', 'Scilab'), ('any', 'any')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('code', 'Code'), ('upload', 'Assignment Upload'), ('integer', 'Answer in Integer'), ('string', 'Answer in String'), ('float', 'Answer in Float')], default='mcq', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionsAuthored', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='questions',
            field=models.ManyToManyField(blank=True, to='LMS.Question'),
        ),
        migrations.AddField(
            model_name='paper',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='LMS.Topic'),
        ),
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papersAuthored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='studyMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='LMS.StudyMaterial'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lmsMaterialLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.Topic'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseCreated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='studyMaterial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='LMS.StudyMaterial'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lmsMaterialComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersSubmssions', to='LMS.Paper'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersSubmssions', to='LMS.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersSubmssions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='LMS.Topic'),
        ),
    ]
