# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:21
from __future__ import unicode_literals

import LMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_auto_20171126_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dp',
            field=models.FileField(null=True, upload_to=LMS.models.getCourseDPAttachmentPath),
        ),
    ]
