# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_auto_20171130_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('moderate', 'moderate'), ('difficult', 'difficult')], max_length=15, null=True),
        ),
    ]
