# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_auto_20171203_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='question',
            name='forReview',
        ),
        migrations.RemoveField(
            model_name='question',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('reviewed', 'reviewed'), ('approved', 'approved')], default='submitted', max_length=20),
        ),
    ]
