# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_auto_20171203_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
    ]
