# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='typ',
            field=models.CharField(choices=[('file', 'file'), ('presentation', 'presentation'), ('video', 'video'), ('quiz', 'quiz'), ('notes', 'notes'), ('announcement', 'announcement')], default='pdf', max_length=20),
        ),
    ]
