# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_auto_20171217_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyMaterials', to='LMS.Course'),
        ),
    ]
