# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_auto_20171229_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveSmallIntegerField()),
                ('optional', models.BooleanField(default=False)),
                ('negativeMarks', models.FloatField()),
                ('ques', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperquestion', to='LMS.Question')),
            ],
        ),
    ]
