# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMS', '0014_auto_20180105_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('marks', models.PositiveSmallIntegerField()),
                ('optional', models.BooleanField(default=False)),
                ('negativeMarks', models.FloatField()),
                ('ques', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperquestion', to='LMS.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paperQuesAuthored', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='questions',
            field=models.ManyToManyField(blank=True, to='LMS.PaperQues'),
        ),
    ]
