# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0017_auto_20180210_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(max_length=20000),
        ),
    ]
