# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0018_auto_20180212_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='version',
            field=models.CharField(default='0.1', max_length=100),
            preserve_default=False,
        ),
    ]
