# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0019_channel_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
