# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0020_feedback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
    ]
