# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LMS', '0021_remove_feedback_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together=set([('user', 'video', 'typ')]),
        ),
    ]
