# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 11:20
from __future__ import unicode_literals

import LMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0022_auto_20180216_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solutionVideo',
            field=models.FileField(null=True, upload_to=LMS.models.getSolutionVideoPath),
        ),
    ]
