# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0024_auto_20180414_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='shortUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
