# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 13:42
from __future__ import unicode_literals

import LMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0025_book_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISSM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Volume',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='dp',
            field=models.FileField(null=True, upload_to=LMS.models.getCourseDPAttachmentPath),
        ),
        migrations.AddField(
            model_name='book',
            name='license',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
