# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0026_auto_20180414_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISSM',
            new_name='ISSN',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Volume',
            new_name='volume',
        ),
    ]
