# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0027_auto_20180414_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sequence',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
