# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0028_section_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typ',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
