# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0030_auto_20180422_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='shortUrl',
        ),
        migrations.AddField(
            model_name='section',
            name='shortUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
