# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0031_auto_20180427_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='shortUrl',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
