# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslip_deffered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='tds',
            field=models.FloatField(),
        ),
    ]
