# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20180317_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.PayrollReport'),
        ),
    ]
