# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='city',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='emergencyContact1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='emergencyContact2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='phoneNo',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='street',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
