# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20180618_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
