# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patients_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='dateOfBirth',
        ),
    ]
