# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.DateTimeField(auto_now_add=True)),
                ('outTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('checkedIn', 'checkedIn'), ('onGoingTreatment', 'onGoingTreatment'), ('operation', 'operation'), ('observation', 'observation'), ('readyToDischarged', 'readyToDischarged'), ('dishcharged', 'dishcharged'), ('settled', 'settled')], default='checkedIn', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceName', models.CharField(max_length=20, null=True)),
                ('grandTotal', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.AddField(
            model_name='patientcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='activePatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activePatient', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='patients.Product'),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='patients.PatientComments'),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.Patient'),
        ),
    ]
