# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20180618_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepatient',
            name='inTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activepatient',
            name='outTime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='activePatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activePatient', to='patients.ActivePatient'),
        ),
    ]
