# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20180619_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepatient',
            name='inTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activepatient',
            name='outTime',
            field=models.DateTimeField(null=True),
        ),
    ]
