# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20180619_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
