# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_remove_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
