# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20180620_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
