# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_invoice_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.AddField(
            model_name='invoice',
            name='data',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
