# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20180620_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='data',
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
