# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20180620_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='modeOfPayment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
