# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_patient_modeofpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='outPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inTime', models.DateTimeField(null=True)),
                ('outTime', models.DateTimeField(null=True)),
                ('particular', models.CharField(max_length=100)),
                ('comments', models.ManyToManyField(blank=True, related_name='outPatientComments', to='patients.PatientComments')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientOut', to='patients.Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='activepatient',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='inPatientComments', to='patients.PatientComments'),
        ),
        migrations.AlterField(
            model_name='activepatient',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientIn', to='patients.Patient'),
        ),
    ]
