# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_dischargesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargesummary',
            name='historyOfAlchohol',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
