# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_auto_20180621_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='activePatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patients.ActivePatient'),
        ),
    ]
