# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_auto_20180622_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargesummary',
            name='patientName',
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dischargeSummary', to='patients.ActivePatient'),
        ),
    ]
