# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_auto_20180622_0354'),
        ('patients', '0028_auto_20180622_0346'),
    ]

    operations = [
    ]
