# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0029_merge_20180622_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpatient',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='outpatient',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='dateOfAdmission',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='dateOfDischarge',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='telephoneNo',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='treatingConsultantContact',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='treatingConsultantDept',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='treatingConsultantName',
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='uhidNo',
        ),
        migrations.AddField(
            model_name='activepatient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='dateOfDischarge',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='modeOfPayment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activepatient',
            name='outPatient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='treatingConsultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hmsPatients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='outPatient',
        ),
    ]
