# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_auto_20180622_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dischargesummary',
            name='treatingConsultant',
        ),
    ]
