# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0032_remove_dischargesummary_treatingconsultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='treatingConsultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hmsPatients', to=settings.AUTH_USER_MODEL),
        ),
    ]
