# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_auto_20180623_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargesummary',
            name='treatingConsultant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patients.Doctor'),
        ),
    ]
