# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0041_activepatient_opno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='activepatient',
            name='docName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outPatients', to='patients.Doctor'),
        ),
    ]
