# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0042_auto_20180625_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activepatient',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='dischargesummary',
            name='treatingConsultant',
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='treatingConsultant',
            field=models.ManyToManyField(null=True, related_name='patients', to='patients.Doctor'),
        ),
    ]
