# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0043_auto_20180625_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargesummary',
            name='treatingConsultant',
            field=models.ManyToManyField(related_name='patients', to='patients.Doctor'),
        ),
    ]
