# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0044_auto_20180625_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepatient',
            name='docName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primaryDoctor', to='patients.Doctor'),
        ),
    ]
