# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0045_auto_20180627_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepatient',
            name='msg',
            field=models.CharField(blank=True, default='Thank You', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='courseInHospital',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
