# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0048_auto_20180627_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargesummary',
            name='advice',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='complaintsAndReason',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='complications',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='courseInHospital',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='familyHistory',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='finalDiagnosis',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='firNo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='historyOfAlchohol',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='keyFindings',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='mlcNo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='pastHistory',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='patientCondition',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='provisionalDiagnosis',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='reviewOn',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='summIllness',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='summaryKeyInvestigation',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='dischargesummary',
            name='treatmentGiven',
            field=models.TextField(blank=True, default='', max_length=4000),
        ),
    ]
