# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiresOn', models.DateField()),
                ('attachment', models.FileField(upload_to=tools.models.getToolsFilePath)),
                ('fileID', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileChaches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
