# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecache',
            name='fileID',
            field=models.CharField(max_length=100),
        ),
    ]
