# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to=tools.models.getToolsFilePath)),
                ('description', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('docID', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filesArchived', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('typ', models.CharField(choices=[('text', 'text'), ('img', 'img')], default='text', max_length=10)),
                ('x', models.FloatField(null=True)),
                ('y', models.FloatField(null=True)),
                ('w', models.FloatField(null=True)),
                ('h', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('title', 'title'), ('para', 'para'), ('footnote', 'footnote'), ('table', 'table'), ('tableHeader', 'tableHeader'), ('other', 'other')], default='other', max_length=10)),
                ('pageNo', models.PositiveIntegerField()),
                ('nlpResult', models.CharField(max_length=3000)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.ArchivedDocument')),
            ],
        ),
    ]
