# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0002_auto_20170518_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('accountType', models.CharField(choices=[('trial', 'trial'), ('community', 'community'), ('commercial', 'commercial')], default='trial', max_length=10)),
                ('remaining', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
