# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_apiaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccount',
            name='apiKey',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apiaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiAccountsCreatedOrOwned', to=settings.AUTH_USER_MODEL),
        ),
    ]
