# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20170521_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
