# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_documentsections'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddocument',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='archiveddocument',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentsections',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tools.ArchivedDocument'),
        ),
    ]
