# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20180509_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archiveddocument',
            old_name='date',
            new_name='dated',
        ),
    ]
