# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_apiaccountlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccountlog',
            name='accActive',
            field=models.BooleanField(default=True),
        ),
    ]
