# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_apiaccountlog_accactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecache',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tools.ApiAccount'),
        ),
        migrations.AlterField(
            model_name='filecache',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileChaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
