# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.PositiveIntegerField()),
                ('dp', models.FileField(upload_to=products.models.getProductDP)),
            ],
        ),
    ]
