# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serial',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
